web:
  build: ./docker/alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./app:/var/www/html
  working_dir: /var/www/html
  links:
    - psql
    # - mysql

# mysql:
#   image: mysql:5.7
#   environment:
#     - MYSQL_ROOT_PASSWORD=drupal
#     - MYSQL_DATABASE=drupal
#     - MYSQL_USER=drupal
#     - MYSQL_PASSWORD=drupal
#     # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#   ports:
#     - "3306:3306"

psql:
  image: kiasaki/alpine-postgres
  environment:
    - POSTGRES_PASSWORD=drupal
    - POSTGRES_USER=drupal
    - POSTGRES_DB=drupal
  # ports:
  #   - "5432:5432"
